version: '2'

services:

  mysql:
    image: mysql:latest
    container_name: metro_mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: "metro"
      MYSQL_ROOT_PASSWORD: "Djwoms18"

  django:
    build: 
      context: .
      dockerfile: ./compose/django/dockerfile
    container_name: metro_django
    depends_on:
      - mysql
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    links:
      - mysql:mysql
